import os

os.environ['CRYPTO_SYMBOLS'] = ['BTCUSDT','EOSUSDT','ETHUSDT','BNBUSDT','ONTUSDT','BCCUSDT','ADAUSDT','XRPUSDT','TUSDUSDT','TRXUSDT','LTCUSDT','ETCUSDT','IOTAUSDT','ICXUSDT','NEOUSDT','VENUSDT','XLMUSDT','QTUMUSDT']
